<a href="https://colab.research.google.com/github/harnalashok/LLMs/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# LAst amended: 2/6/2024
# Ref: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
import torch
import numpy as np

In [4]:
x = [[1,2], [3,4]]
y = torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]])

In [7]:
x = [[1,2], [3,4]]
x = np.array([x])
y = torch.tensor(x)
y

tensor([[[1, 2],
         [3, 4]]])

In [8]:
x = [[1,2], [3,4]]
x = np.array([x])
y = torch.from_numpy(x)
y

tensor([[[1, 2],
         [3, 4]]])

In [10]:
x_ones = torch.ones_like(y) # retains the properties of y
print(f"Ones Tensor: \n {x_ones} \n")



Ones Tensor: 
 tensor([[[1, 1],
         [1, 1]]]) 



In [13]:
x_rand = torch.rand_like( y, dtype = torch.float )
print(f"x_rand: \n {x_rand} \n")

x_rand: 
 tensor([[[0.9561, 0.3087],
         [0.0916, 0.6443]]]) 



In [25]:
shape = (2,3,)

print(torch.rand(shape))
print(torch.ones(shape))
print(torch.zeros(shape))

tensor([[0.8073, 0.7621, 0.6772],
        [0.8579, 0.8035, 0.2128]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3491, 0.6481, 0.4756],
        [0.1427, 0.5165, 0.7917]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
rd = torch.rand(3,4)
on = torch.ones(4,5)
ze = torch.zeros(3,4)
print(rd.shape)
print(on.dtype)
print(ze.device)

torch.Size([3, 4])
torch.float32
cpu


In [32]:
torch.cuda.is_available()

False