<a href="https://colab.research.google.com/github/harnalashok/LLMs/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# LAst amended: 2/6/2024
# Ref: https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [1]:
import torch
import numpy as np

In [4]:
x = [[1,2], [3,4]]
y = torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]])

In [7]:
x = [[1,2], [3,4]]
x = np.array([x])
y = torch.tensor(x)
y

tensor([[[1, 2],
         [3, 4]]])

In [8]:
x = [[1,2], [3,4]]
x = np.array([x])
y = torch.from_numpy(x)
y

tensor([[[1, 2],
         [3, 4]]])